import React from "react";
import BreadcrumbComp from "@/components/layout/shared/breadcrumb/BreadcrumbComp";
import FollowersChart from "@/components/widgets/charts/FollowersChart";
import ViewsChart from "@/components/widgets/charts/ViewsChart";
import EarnedChart from "@/components/widgets/charts/EarnedChart";
import TotalEarningChart from "@/components/widgets/charts/TotalEarnigs";
import CurrentValue from "@/components/widgets/charts/CurrentValue";
import YarlyBreakup from "@/components/widgets/charts/YarlyBreakup";
import MonthlyEarning from "@/components/widgets/charts/MonthlyEarcning";
import MostVisited from "@/components/widgets/charts/MostVisited";
import YearlySales from "@/components/widgets/charts/YearlySales";
import PageImpression from "@/components/widgets/charts/PageImpression";
import Customers from "@/components/widgets/charts/Customers";
import Projects from "@/components/widgets/charts/Projects";
import RevenueUpdates from "@/components/widgets/charts/RevenueUpdates";
import SalesOverview from "@/components/widgets/charts/SalesOverview";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Chart Widgets",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Charts",
  },
];
const Charts = () => {
  return (
    <>
      <BreadcrumbComp title="Charts" items={BCrumb} />
      <div className="grid grid-cols-12 gap-[30px]">
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <FollowersChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <ViewsChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <EarnedChart />
        </div>
        <div className="lg:col-span-3 md:col-span-6 col-span-12">
          <TotalEarningChart />
        </div>
        <div className="col-span-12">
          <CurrentValue />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <YarlyBreakup />
          <MonthlyEarning />
          <MostVisited />
        </div>
        <div className="lg:col-span-4 col-span-12">
          <YearlySales />
          <PageImpression />
          <div className="grid grid-cols-12 gap-[30px] mt-[30px]">
            <div className="sm:col-span-6 col-span-12">
              <Customers />
            </div>
            <div className="sm:col-span-6 col-span-12">
              <Projects />
            </div>
          </div>
        </div>
        <div className="lg:col-span-4 col-span-12">
          <RevenueUpdates />
          <SalesOverview />
        </div>
      </div>
    </>
  );
};

export default Charts;
